services:
  pytorch_fastapi:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
        APP_DIR_NAME: ${APP_DIR_NAME}      
        GIT_URI: ${GIT_URI}      
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
      - 8000:8000
    depends_on:
      - mongodb
    command: sleep infinity
  mongodb:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0      
