services:
  gatheringdatas:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
        APP_DIR_NAME: ${APP_DIR_NAME}      
        GIT_URI: ${GIT_URI}      
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    command: sleep infinity
  db_mongodb_7:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0      
