version: "3.8"

services:
  postgres_16.3:
    image: postgres:16.3
    # container_name: cocolabhub-db
    environment:
      POSTGRES_DB: cocolabhub
      POSTGRES_USER: cocolabhub
      POSTGRES_PASSWORD: cocolabhub
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
